version: '3.9'

services:
  mysql:
    image: mysql:8
    container_name: mysql-prueba
    restart: always
    environment:
      MYSQL_DATABASE: prueba
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - '3308:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - '5672:5672'     
      - '15672:15672'  
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

  microservicio1:
    build:
      context: ./microservicio1_pruebatecnica
    container_name: microservicio1
    ports:
      - '8081:8081'
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-prueba:3306/prueba
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123
    networks:
      - app-network

  microservicio2:
    build:
      context: ./microservicio2_pruebatecnica
    container_name: microservicio2
    ports:
      - '8082:8082'
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-prueba:3306/prueba
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_RABBITMQ_HOST: rabbitmq   
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
